# Custom redirects to block users from certain countries from using the app
# The list of countries we've decided to block is the OFAC sanctioned countries
# See full list of blocked countries: https://www.countryipblocks.net/ofac.php
[[redirects]]
  from = "/*"
  to = "/unavailable.html"
  status = 302
  force = true
  conditions = {Country = ['BY', 'BA', 'BI', 'CF', 'CD', 'CU', 'IR', 'IQ', 'KP', 'XK', 'LB', 'LY', 'MK', 'NI', 'RU', 'SO', 'SS', 'SD', 'SY', 'UA', 'VE', 'YE', 'ZW']}

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

# Production context:
[context.production]
  command = "npm run build-prod"
  # Deploys from main branch run this plugin in the build.
  # Plugins context requires double brackets.
  [[context.production.plugins]]
    package = "@netlify/plugin-sitemap"

# Test production context:
# testprod branch is a replication of main before being pushed out
[context.testprod]
  command = "npm run build-prod"

# Deploy Preview context:
# All deploys generated from a pull/merge request
# will inherit these settings.
[context.deploy-preview.environment]
  command = "npm run build-dev"

# Branch deploy context:
# All deploys that are not from a pull/merge request
# or from the production branch will inherit these settings.
# [context.branch-deploy]
#   command = "npm run build-dev"

# Staging context:
# Branch for testing staging contracts (testnet)
[context.staging]
  command = "npm run build-staging"

# This is our public dev branch which deploys a publicly accessible site
# with dev networks
[context.development]
  command = "npm run build-dev"